spring:
  application:
    name: vertx-jcache
  datasource:
    url: jdbc:mysql://localhost:3306/AccountBook
    username: root
    password: 0dong2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          hazelcast:
            use_native_client: true
            native_client_address: 127.0.0.1:5701
            native_client_group: dev
            native_client_password: dev-pass
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
        generate_statistics: true

logging:
  level:
    com.hazelcast: DEBUG
    org.hibernate:
      SQL: DEBUG