spring:
  application:
    name: vertx-jcache
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mtalk?useSSL=false
    username: root
    password: 0dong2
  jpa:
    properties:
      hibernate:
        show_sql: true
        cache:
          use_query_cache: true
          use_second_level_cache: true
          hazelcast:
            use_native_client: true
            native_client_address: 127.0.0.1:5701
            native_client_group: dev
            native_client_password: dev-pass
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory